<?php
return array(
    $icons = array(
    'bi-123' => '123',
    'bi-alarm-fill' => 'Alarm Fill',
    'bi-alarm' => 'Alarm',
    'bi-align-bottom' => 'Align Bottom',
    'bi-align-center' => 'Align Center',
    'bi-align-end' => 'Align End',
    'bi-align-middle' => 'Align Middle',
    'bi-align-start' => 'Align Start',
    'bi-align-top' => 'Align Top',
    'bi-alt' => 'Alt',
    'bi-app-indicator' => 'App Indicator',
    'bi-app' => 'App',
    'bi-archive-fill' => 'Archive Fill',
    'bi-archive' => 'Archive',
    'bi-arrow-90deg-down' => 'Arrow 90deg Down',
    'bi-arrow-90deg-left' => 'Arrow 90deg Left',
    'bi-arrow-90deg-right' => 'Arrow 90deg Right',
    'bi-arrow-90deg-up' => 'Arrow 90deg Up',
    'bi-arrow-bar-down' => 'Arrow Bar Down',
    'bi-arrow-bar-left' => 'Arrow Bar Left',
    'bi-arrow-bar-right' => 'Arrow Bar Right',
    'bi-arrow-bar-up' => 'Arrow Bar Up',
    'bi-arrow-clockwise' => 'Arrow Clockwise',
    'bi-arrow-counterclockwise' => 'Arrow Counterclockwise',
    'bi-arrow-down-circle-fill' => 'Arrow Down Circle Fill',
    'bi-arrow-down-circle' => 'Arrow Down Circle',
    'bi-arrow-down-left-circle-fill' => 'Arrow Down Left Circle Fill',
    'bi-arrow-down-left-circle' => 'Arrow Down Left Circle',
    'bi-arrow-down-left-square-fill' => 'Arrow Down Left Square Fill',
    'bi-arrow-down-left-square' => 'Arrow Down Left Square',
    'bi-arrow-down-left' => 'Arrow Down Left',
    'bi-arrow-down-right-circle-fill' => 'Arrow Down Right Circle Fill',
    'bi-arrow-down-right-circle' => 'Arrow Down Right Circle',
    'bi-arrow-down-right-square-fill' => 'Arrow Down Right Square Fill',
    'bi-arrow-down-right-square' => 'Arrow Down Right Square',
    'bi-arrow-down-right' => 'Arrow Down Right',
    'bi-arrow-down-short' => 'Arrow Down Short',
    'bi-arrow-down-square-fill' => 'Arrow Down Square Fill',
    'bi-arrow-down-square' => 'Arrow Down Square',
    'bi-arrow-down-up' => 'Arrow Down Up',
    'bi-arrow-down' => 'Arrow Down',
    'bi-arrow-left-circle-fill' => 'Arrow Left Circle Fill',
    'bi-arrow-left-circle' => 'Arrow Left Circle',
    'bi-arrow-left-right' => 'Arrow Left Right',
    'bi-arrow-left-short' => 'Arrow Left Short',
    'bi-arrow-left-square-fill' => 'Arrow Left Square Fill',
    'bi-arrow-left-square' => 'Arrow Left Square',
    'bi-arrow-left' => 'Arrow Left',
    'bi-arrow-repeat' => 'Arrow Repeat',
    'bi-arrow-return-left' => 'Arrow Return Left',
    'bi-arrow-return-right' => 'Arrow Return Right',
    'bi-arrow-right-circle-fill' => 'Arrow Right Circle Fill',
    'bi-arrow-right-circle' => 'Arrow Right Circle',
    'bi-arrow-right-short' => 'Arrow Right Short',
    'bi-arrow-right-square-fill' => 'Arrow Right Square Fill',
    'bi-arrow-right-square' => 'Arrow Right Square',
    'bi-arrow-right' => 'Arrow Right',
    'bi-arrow-up-circle-fill' => 'Arrow Up Circle Fill',
    'bi-arrow-up-circle' => 'Arrow Up Circle',
    'bi-arrow-up-left-circle-fill' => 'Arrow Up Left Circle Fill',
    'bi-arrow-up-left-circle' => 'Arrow Up Left Circle',
    'bi-arrow-up-left-square-fill' => 'Arrow Up Left Square Fill',
    'bi-arrow-up-left-square' => 'Arrow Up Left Square',
    'bi-arrow-up-left' => 'Arrow Up Left',
    'bi-arrow-up-right-circle-fill' => 'Arrow Up Right Circle Fill',
    'bi-arrow-up-right-circle' => 'Arrow Up Right Circle',
    'bi-arrow-up-right-square-fill' => 'Arrow Up Right Square Fill',
    'bi-arrow-up-right-square' => 'Arrow Up Right Square',
    'bi-arrow-up-right' => 'Arrow Up Right',
    'bi-arrow-up-short' => 'Arrow Up Short',
    'bi-arrow-up-square-fill' => 'Arrow Up Square Fill',
    'bi-arrow-up-square' => 'Arrow Up Square',
    'bi-arrow-up' => 'Arrow Up',
    'bi-arrows-angle-contract' => 'Arrows Angle Contract',
    'bi-arrows-angle-expand' => 'Arrows Angle Expand',
    'bi-arrows-collapse' => 'Arrows Collapse',
    'bi-arrows-expand' => 'Arrows Expand',
    'bi-arrows-fullscreen' => 'Arrows Fullscreen',
    'bi-arrows-move' => 'Arrows Move',
    'bi-aspect-ratio-fill' => 'Aspect Ratio Fill',
    'bi-aspect-ratio' => 'Aspect Ratio',
    'bi-asterisk' => 'Asterisk',
    'bi-at' => 'At',
    'bi-award-fill' => 'Award Fill',
    'bi-award' => 'Award',
    'bi-back' => 'Back',
    'bi-backspace-fill' => 'Backspace Fill',
    'bi-backspace-reverse-fill' => 'Backspace Reverse Fill',
    'bi-backspace-reverse' => 'Backspace Reverse',
    'bi-backspace' => 'Backspace',
    // 👉 isi pattern me tum full list continue kar sakte ho
);
    // 👉 yahan aur add karte jao (ya script se generate kar sakte ho)
);
function get_custom_icons() {
    return array(
        'custom-gold-bull' => 'Gold Bull Icon',
        'custom-chart'     => 'Chart Icon',
    );
}